language: node_js
node_js:
- 12
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  directories:
  - "~/.yarn"
  - "~/.cache"
script:
- yarn test
- yarn build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: jXEtlGYiNRARtWeZdSrXe/WtpvnTJ8pNXJzk72xDnwGsQcsDV6AxgRe048CgkMrzQL5PyZQehOVaY0YJkIvLr7cwfTDqjsG7d3HL0JZEeKkBkeyolg+PAuyfOxa+ZyfhcTbYd4WzUSnvgQUU/8J3vLsVenXrGeBDijVf1bG4kWtNEPaLKFlxt+bIONbQbfOIdlk4WiQFEKNAXR7glCgP6Rla4tjdbb1MWidV4BOD7NRRFffw2zGeE8i6+MmQx+xK4zBJuN1g+x+/HirLzJ8IdxFZBLUs5BkEw+Iilf+mQAXdGhP1zMtOxcCjDT5fSF7W7/7b2Pr3ZrZrBDDnbC1YL5odXOqKP3d66StoR6dofd3W1YAeb+FLAxshXpH5gyXWwcIGw89VW+pfvOPQ9k4hDPS3BLWlIO5mkkUNYMnBcjFmPV+9JkO1ZHAklZPCGVsFlhjcs3lAgaEaUlsuRvrfl/wKTWPkCTRb0bVJ6rRr73KQGh6BHfhA3CtefTBGiktDB1YLa1j6lgxp0m4DB/FojHK3KP+gYSr74bWifBI+ZWqx3ce6aEfW4H4yiHfTyorusetC2LCwcGqB6F5wlIn3fcJe5x4VW7fkEXz/phCG1IhA4A0KfYy2CGqCscw7l/OgrKDMOaooZfaV5avVGgKABcR7+WR56yINnn5tIFPI1y4=

